import "../styles/globals.css"
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata = {
  title: "MeetUsVR",
  description: "Generated by MeetUsVR",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <AntdRegistry>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
